name: ActualizaDataInstrumentos

on:
  schedule:
    - cron: '45 0 * * *'  # 01:00 UTC = 20:45 Venezuela
  workflow_dispatch:

permissions:
  contents: write

jobs:
  ejecutar:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar script principal
        run: python main.py
        env:
          API_KEY: ${{ secrets.API_KEY }}

      - name: Configurar Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      - name: Commit y push de cambios
        run: |
          git add db/btcusd-D1_2010-07-17_actualidad.parquet
          git add db/eurusd-D1_2000-01-03_actualidad.parquet
          git add db/sp500-D1_2000-01-03_actualidad.parquet
          git add db/us10y-D1_2000-01-03_actualidad.parquet
          git add db/xauusd-D1_2000-01-03_actualidad.parquet
          git commit -m "Actualización automática: $(date '+%Y-%m-%d %H:%M')" || echo "Sin cambios para commitear"
          git push
